Move checks after option handling

diff --git a/bin/pw-edit b/bin/pw-edit
--- a/bin/pw-edit
+++ b/bin/pw-edit
@@ -8,13 +8,6 @@ LIB_DIR="`dirname $0`/../lib/pw"
 . "${LIB_DIR}/configuration.sh"
 . "${LIB_DIR}/functions.sh"
 
-check_opts () {
-	[ -n "$handle" ] || {
-		echo "ERROR: The HANDLE of the entry to be modified has not been provided." >&2
-		return 1
-	}
-}
-
 help () {
 	cat <<-EOD
 		Usage: pw-edit [OPTION] HANDLE
@@ -51,6 +44,13 @@ while [ $# -gt 0 ] ; do
 	shift
 done
 [ $# -ne 0 ] && handle=$1
+
+check_opts () {
+	[ -n "$handle" ] || {
+		echo "ERROR: The HANDLE of the entry to be modified has not been provided." >&2
+		return 1
+	}
+}
 
 check_opts
 
diff --git a/bin/pw-insert b/bin/pw-insert
--- a/bin/pw-insert
+++ b/bin/pw-insert
@@ -8,14 +8,6 @@ LIB_DIR="`dirname $0`/../lib/pw"
 . "${LIB_DIR}/configuration.sh"
 . "${LIB_DIR}/functions.sh"
 
-check_config () {
-	[ "${GPG_KEY-unset}" != "unset" ] || {
-		echo "ERROR: GPG_KEY not set" >&2
-		echo "Set GPG_KEY in $CONFIG_FILE" >&2
-		return 1
-	}
-}
-
 help () {
 	cat <<-EOD
 		Usage: pw-insert [OPTION] [LABEL]"
@@ -49,6 +41,14 @@ while [ $# -gt 0 ] ; do
 	shift
 done
 [ $# -ne 0 ] && label=$1
+
+check_config () {
+	[ "${GPG_KEY-unset}" != "unset" ] || {
+		echo "ERROR: GPG_KEY not set" >&2
+		echo "Set GPG_KEY in $CONFIG_FILE" >&2
+		return 1
+	}
+}
 
 check_config
 
diff --git a/bin/pw-show b/bin/pw-show
--- a/bin/pw-show
+++ b/bin/pw-show
@@ -8,18 +8,6 @@ LIB_DIR="`dirname $0`/../lib/pw"
 . "${LIB_DIR}/configuration.sh"
 . "${LIB_DIR}/functions.sh"
 
-check_args () {
-	if [ -n "$search_field" -a -z "$pattern" ] ; then
-		echo "ERROR: requested to search in field \`\`$search_field'' but no PATTERN specified." >&2
-		exit 1
-	fi
-
-	if [ -n "$show_field" ] && $opt_complete_output ; then
-		echo "ERROR: requested to show only field \`\`$show_field'' but also all fields." >&2
-		exit 1
-	fi
-}
-
 help () {
 	cat <<-EOD
 	Usage: pw-show [OPTION] [PATTERN]
@@ -64,6 +52,18 @@ while [ $# -gt 0 ] ; do
 done
 [ $# -ne 0 ] && pattern=$1
 [ -z "$pattern" ] && opt_show_all=true
+
+check_args () {
+	if [ -n "$search_field" -a -z "$pattern" ] ; then
+		echo "ERROR: requested to search in field \`\`$search_field'' but no PATTERN specified." >&2
+		exit 1
+	fi
+
+	if [ -n "$show_field" ] && $opt_complete_output ; then
+		echo "ERROR: requested to show only field \`\`$show_field'' but also all fields." >&2
+		exit 1
+	fi
+}
 
 check_args
 
