Search for databases in XDG_DATA_HOME

diff --git a/test/show b/test/show
--- a/test/show
+++ b/test/show
@@ -14,8 +14,19 @@ $PW_SHOW -d /dev/null && ok || failed
 echo "...does not accept directories"
 $PW_SHOW -d /tmp && failed || ok
 
-echo "...complains about missing dbs"
+echo "...complains about missing dbs (absolute)"
 $PW_SHOW -d /tmp/does-not-exist && failed || ok
+
+echo "...complains about missing dbs (relative)"
+$PW_SHOW -d does-not-exist && failed || ok
+
+echo "...searches dbs in XDG_DATA_HOME"
+mkdir -p /tmp/xdg/pw
+cp ${fixtures_dir}/good /tmp/xdg/pw
+XDG_DATA_HOME=/tmp/xdg $PW_SHOW -d good && ok || failed
+rm /tmp/xdg/pw/good
+rmdir /tmp/xdg/pw
+rmdir /tmp/xdg
 
 echo "...with no params shows all records"
 num_records=$($PW_SHOW -d ${fixtures_dir}/good | wc -l)
