Avoid false error reports when searching with --all

diff --git a/test/show b/test/show
--- a/test/show
+++ b/test/show
@@ -36,8 +36,17 @@ echo "...complains about broken records but goes on"
 num_records=$($PW_SHOW -d ${fixtures_dir}/bad | wc -l)
 [ "$num_records" -eq 5 ] && ok || failed
 
+echo "...does not return an error if a matching entry can be found"
+$PW_SHOW_GOOD 'entry1' && ok || failed
+
+echo "...does not return an error if multiple entries can be found"
+$PW_SHOW_GOOD --all 'entry' && ok || failed
+
 echo "...returns an error if it cannot find any matching entry"
 $PW_SHOW_GOOD 'non-existing' && failed || ok
+
+echo "...returns an error if it cannot find any matching entry (with --all)"
+$PW_SHOW_GOOD --all 'non-existing' && failed || ok
 
 echo "...searches on all fields"
 pw=$($PW_SHOW_GOOD 'hidden-entry6')
